pipeline:
  name: ci-eureka
  identifier: cieureka
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: eurekamahesh
        build: <+input>
  stages:
    - stage:
        name: build-and-push
        identifier: buildandpush
        description: Build and push Docker image
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    shell: Sh
                    command: |-
                      mvn clean package -DskipTests=true
                      ls -lrt target
              - step:
                  type: ArtifactoryUpload
                  name: ArtifactoryUpload_1
                  identifier: ArtifactoryUpload_1
                  spec:
                    connectorRef: mahesh_jfrog
                    target: maven-build-libs-snapshot/
                    sourcePath: target/i27-eureka-0.0.1-SNAPSHOT.jar
              - step:
                  type: Run
                  name: docker-login
                  identifier: dockerlogin
                  spec:
                    shell: Sh
                    command: |-
                      # Retrieve Docker Hub credentials from Vault
                      export DOCKER_USERNAME=$(vault kv get -field=username secret/docker)
                      export DOCKER_PASSWORD=$(vault kv get -field=password secret/docker)
                      # Login to Docker Hub non-interactively
                      echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
              - step:
                  type: Run
                  name: docker-build
                  identifier: dockerbuild
                  spec:
                    shell: Sh
                    command: docker build -t mahesh .
              - step:
                  type: Run
                  name: docker-tag
                  identifier: dockertag
                  spec:
                    shell: Sh
                    command: docker tag mahesh:latest mkodalihr400/vault-harness-integration:latest
              - step:
                  type: Run
                  name: docker-push
                  identifier: dockerpush
                  spec:
                    shell: Sh
                    command: docker push mkodalihr400/vault-harness-integration:latest
              - step:
                  type: Run
                  name: cleanup
                  identifier: cleanup
                  spec:
                    shell: Sh
                    command: |-
                      # Any necessary clean up steps
                      echo "Cleanup complete"
