pipeline:
  name: eureka
  identifier: eureka
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: eurekamahesh
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    shell: Sh
                    command: |-
                      mvn clean package -DskipTests=true
                      ls -lrt target
              - step:
                  type: ArtifactoryUpload
                  name: ArtifactoryUpload_1
                  identifier: ArtifactoryUpload_1
                  spec:
                    connectorRef: mahesh_jfrog
                    target: maven-build-libs-snapshot/com/example/eureka/0.0.1-SNAPSHOT/i27-eureka-0.0.1-SNAPSHOT.jar
                    sourcePath: target/i27-eureka-0.0.1-SNAPSHOT.jar
