pipeline:
  name: eureka
  identifier: eureka
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: eurekamahesh
        build: <+input>
  stages:
    - stage:
        name: build-artifact
        identifier: buildartifact
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: maven_build
                  identifier: maven_build
                  spec:
                    shell: Sh
                    image: maven:3.8.6-openjdk-17
                    command: |
                      mvn clean package -DskipTests=true
