pipeline:
  name: eureka
  identifier: eureka
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: eurekamahesh
        build: <+input>
  stages:
    - stage:
        name: build-artifact
        identifier: buildartifact
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: maven_build
                  identifier: maven_build
                  spec:
                    shell: Sh
                    command: |-
                      sudo apt install openjdk-17-jdk
                      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
                      export PATH=$JAVA_HOME/bin:$PATH
                      java -version
                      mvn clean package -DskipTests=true
